name: "Unit tests"

on:
    pull_request:
        branches:
            - "master"
    push:
        branches:
            - "master"

jobs:
    unit-test:
        name: "Unit tests"
        runs-on: "ubuntu-20.04"
        strategy:
            matrix:
                php-version:
                    - "7.3"
                    - "7.4"
                    - "8.0"
        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2"
            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php-version }}"

            - name: "Install dependencies with Composer"
              uses: "ramsey/composer-install@v1"
              with:
                  composer-options: "--ignore-platform-reqs"

            - name: "Run PHPUnit"
              run: "vendor/bin/phpunit --configuration phpunit.xml.dist"

            - name: "Init Laminas test app"
              working-directory: "./tests/laminas-runner"
              run: "./install.sh"
            - name: "Run Laminas integration test"
              working-directory: "./tests/laminas-runner/app"
              run: "php test.php"

            - name: "Init Mezzio test app"
              working-directory: "./tests/mezzio-runner"
              run: "./install.sh"
            - name: "Run Mezzio integration test"
              working-directory: "./tests/mezzio-runner/app"
              run: "php test.php"
